[package]
name = "biblioteca"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
serde = "1.0.219"
uuid = { version = "1.16.0", features = ["serde", "v4"] }

